# code was made by Microsoft CoPilot for testing

name: S3 Bucket Management

on:
  push:
    paths:
      - 'path/to/s3/file/**/*'

jobs:
  manage-s3:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Create unique S3 bucket
      env:
        BUCKET_NAME: my-bucket-${{ github.run_number }}
      run: |
        aws s3 mb s3://$BUCKET_NAME

  review-merge:
    runs-on: ubuntu-latest
    needs: manage-s3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run tests
      run: |
        npm install
        npm test

    - name: Static analysis
      run: |
        npm run lint      
      
    - name: Approval check
      if: success()
      run: echo "All checks passed. Ready to merge."

    - name: Merge PR
      if: success()
      uses: actions/github-script@v5
      with:
        script: |
          github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            merge_method: 'squash'
          })

  delete-s3:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    needs: review-merge

    steps:
    - name: Delete S3 bucket
      env:
        BUCKET_NAME: my-bucket-${{ github.run_number }}
      run: |
        aws s3 rb s3://$BUCKET_NAME --force
        aws cloudformation wait stack-delete-complete --bucket $BUCKET_NAME
